# Use the official Node.js as the base image
FROM node:22.15.0-bookworm-slim

# Install curl
RUN apt-get update && \
    apt-get install -y curl --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

RUN addgroup --system --gid 1001 ops
RUN adduser --system --uid 1001 ops

WORKDIR /app

COPY package*.json ./
COPY packages/ ./packages/
COPY services/gatekeeper/client/package*.json ./gatekeeper/client/
COPY services/gatekeeper/server/package*.json ./gatekeeper/server/

RUN --mount=type=cache,target=/root/.npm npm ci --ignore-scripts
RUN --mount=type=cache,target=/root/.npm cd gatekeeper/client && npm ci --include=dev
RUN --mount=type=cache,target=/root/.npm cd gatekeeper/server && npm ci

COPY services/gatekeeper ./gatekeeper/

RUN npm rebuild sqlite3
RUN npm run build
RUN cd gatekeeper/client && npm run build
RUN cd gatekeeper/server && npm run build

FROM node:22.15.0-bookworm-slim

WORKDIR /app
COPY --from=builder /app /app

WORKDIR /app/gatekeeper
RUN chown -R ops:ops /app
USER ops

# Run...
CMD ["node", "server/dist/gatekeeper-api.js"]