# Use the official Node.js as the base image
FROM node:22.15.0-bookworm-slim

# Install curl
RUN apt-get update && \
    apt-get install -y curl --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./
COPY packages/ ./packages/

ARG VITE_EXPLORER_PORT
ARG VITE_GATEKEEPER_URL
ARG VITE_SEARCH_SERVER

ENV VITE_EXPLORER_PORT=${VITE_EXPLORER_PORT}
ENV VITE_GATEKEEPER_URL=${VITE_GATEKEEPER_URL}
ENV VITE_SEARCH_SERVER=http://development-search.mastodon-bushi.ts.net:4002

# Install dependencies
RUN npm ci --ignore-scripts
RUN npm rebuild sqlite3
RUN npm run build

COPY services/explorer ./explorer/

WORKDIR /app/explorer

RUN npm i
RUN npm run build

EXPOSE 4000

# Run...
CMD ["node", "server.js"]