# Use the official Node.js as the base image
FROM node:22.15.0-bookworm-slim

RUN addgroup --system --gid 1001 ops
RUN adduser --system --uid 1001 ops

WORKDIR /app

COPY package*.json ./
COPY packages/ ./packages/
COPY services/mediators/satoshi-inscription/package*.json ./satoshi/
COPY services/mediators/satoshi-inscription/patches/ ./satoshi/patches/

# Install dependencies
RUN npm ci
RUN npm rebuild sqlite3
RUN npm run build

COPY services/mediators/satoshi-inscription ./satoshi/

RUN chown -R ops:ops /app
USER ops

# Run...
CMD ["node", "dist/inscription-mediator.js"]