# syntax=docker/dockerfile:1

FROM node:22.15.0-bookworm-slim AS builder

# Install curl
RUN apt-get update && \
    apt-get install -y curl --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

RUN addgroup --system --gid 1001 ops
RUN adduser --system --uid 1001 ops

WORKDIR /app

COPY package*.json ./
COPY packages/ ./packages/
COPY services/search-server/package*.json ./search-server/

RUN --mount=type=cache,target=/root/.npm npm ci --ignore-scripts
RUN --mount=type=cache,target=/root/.npm cd search-server && npm ci

COPY services/search-server ./search-server/

# Install dependencies
RUN npm ci
RUN npm run build
RUN cd search-server && npm run build

# Make sure dir is owned by user who will build
RUN chown -R ops:ops /app/search-server

# Switch to ops user
USER ops

WORKDIR /app/search-server

EXPOSE 4002

# Run...
CMD ["node", "dist/index.js"]